# Advanced Load Balancer Configuration for Traefik Gateway
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: backend1-loadbalancer
  namespace: traefik-gateway
spec:
  weighted:
    services:
    - name: backend1-service
      weight: 100
    - name: backend1-backup-service
      weight: 0
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: backend2-loadbalancer
  namespace: traefik-gateway
spec:
  weighted:
    services:
    - name: backend2-service
      weight: 100
    - name: backend2-backup-service
      weight: 0
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: backend3-loadbalancer
  namespace: traefik-gateway
spec:
  weighted:
    services:
    - name: backend3-service
      weight: 100
    - name: backend3-backup-service
      weight: 0
---
# Round Robin Load Balancer Configuration
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: round-robin-backend1
  namespace: traefik-gateway
spec:
  loadBalancer:
    servers:
    - url: "http://backend1-service:3000"
    - url: "http://backend1-backup-service:3000"
    healthCheck:
      path: "/health"
      interval: "10s"
      timeout: "5s"
      retries: 3
    sticky:
      cookie:
        name: "backend1-sticky"
        secure: true
        httpOnly: true
---
# Circuit Breaker Middleware
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: advanced-circuitbreaker
  namespace: traefik-gateway
spec:
  circuitBreaker:
    expression: "NetworkErrorRatio() > 0.3 || ResponseCodeRatio(500, 600, 0, 600) > 0.3"
    checkPeriod: "10s"
    fallbackDuration: "30s"
    recoveryDuration: "10s"
---
# Retry Middleware
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: retry-middleware
  namespace: traefik-gateway
spec:
  retry:
    attempts: 3
    initialInterval: "100ms"
---
# Buffer Middleware
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: buffer-middleware
  namespace: traefik-gateway
spec:
  buffering:
    maxRequestBodyBytes: 10485760  # 10MB
    memRequestBodyBytes: 2097152   # 2MB
    maxResponseBodyBytes: 10485760 # 10MB
    memResponseBodyBytes: 2097152  # 2MB
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
# Advanced Rate Limiting
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: advanced-ratelimit
  namespace: traefik-gateway
spec:
  rateLimit:
    burst: 200
    average: 100
    period: "1m"
    sourceCriterion:
      ipStrategy:
        depth: 1
        excludedIPs:
        - "127.0.0.1/32"
        - "10.0.0.0/8"
---
# Load Balancing Strategy Configuration
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: loadbalancer-strategy
  namespace: traefik-gateway
spec:
  loadBalancer:
    method: "roundrobin"
    sticky:
      cookie:
        name: "traefik-sticky"
        secure: true
        httpOnly: true
        sameSite: "strict"
