apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-gateway
  namespace: traefik-gateway
  labels:
    app: traefik-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik-gateway
  template:
    metadata:
      labels:
        app: traefik-gateway
    spec:
      containers:
      - name: traefik
        image: traefik:v3.0
        ports:
        - containerPort: 80
          name: web
        - containerPort: 443
          name: websecure
        - containerPort: 8080
          name: dashboard
        args:
        - --api.dashboard=true
        - --api.insecure=true
        - --providers.kubernetesingress=true
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --certificatesresolvers.letsencrypt.acme.email=admin@apifincheck.husanenglish.online
        - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
        - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
        - --entrypoints.web.http.redirections.entrypoint.to=websecure
        - --entrypoints.web.http.redirections.entrypoint.scheme=https
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-gateway
  namespace: traefik-gateway
  labels:
    app: traefik-gateway
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: websecure
    port: 443
    targetPort: 443
  - name: dashboard
    port: 8888
    targetPort: 8080
  selector:
    app: traefik-gateway
